/**
 * GoLogin management — creating, editing and deleting profiles; creating,
 * deleting and filling folders; and sharing both with members.
 *
 * Everything here speaks as the **master** workspace (`getMasterGoLoginClient`),
 * the same identity the Members surface already uses. A non-admin with the right
 * capability administers the workspace *server-side*; they never hold the master
 * token (see gologin.md § Admins use the master token).
 *
 * ## The fingerprint is the thing being protected
 *
 * A GoLogin profile is a disguise for a live, logged-in social account, and the
 * disguise is only as good as its consistency. GoLogin's own guidance is that OS,
 * user agent, resolution, fonts, canvas, WebGL and CPU/RAM must **never change
 * after an account has logged in**. Three decisions here follow from that:
 *
 *   1. **Create is `POST /browser/quick`** — GoLogin's "profile on the default
 *      settings" — so the fingerprint is generated by GoLogin, consistently, for
 *      the chosen OS. Nothing here assembles one by hand.
 *   2. **No edit ever calls `PUT /browser/{id}/custom`**, which re-randomises
 *      every parameter the body omits. Name, proxy and folders each go through an
 *      endpoint that touches only that field; notes go through the SDK's own
 *      read-whole-document-write-it-back update.
 *   3. **A profile never exists without the proxy it was created for.** If
 *      attaching the proxy fails, the new profile is deleted rather than left on
 *      the operator's real IP for someone to launch.
 *
 * ## The request budget
 *
 * Every call here is a provider request, and a 429 revokes the master token for
 * good (rule 9e). Everything is sequential, bounded by the batch caps in the
 * routes, and reads come from the 60s memos in `gologinAccountService`.
 * Membership writes patch that memo in place (`applyFolderMembership`) rather
 * than dropping it — only structural changes (a folder created or deleted, a
 * profile created or deleted) force the next `GET /user`.
 */
import 'server-only';
import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase-admin';
import {
  getMasterGoLoginClient,
  GOLOGIN_MEMBER_ROLE,
  GOLOGIN_OS_CHOICES,
  isGoLoginProxyMode,
  isManagedGoLoginFolder,
  type GoLoginAccountInfo,
  type GoLoginFolder,
  type GoLoginFolderRow,
  type GoLoginOsChoice,
  type GoLoginProfile,
  type GoLoginProfileDetail,
  type GoLoginProxyInput,
  type GoLoginSharingMember,
  type GoLoginSharingOverview,
} from '@/lib/gologin';
import {
  applyFolderMembership,
  findMember,
  getMasterAccount,
  getWorkspace,
  getWorkspaceId,
  GOLOGIN_ACCOUNTS_COLLECTION,
  invalidateMasterAccount,
  invalidateWorkspace,
  isGoLoginAdmin,
  usesMasterGoLoginToken,
  type GoLoginAccountDoc,
} from '@/lib/services/gologinAccountService';
import {
  changeAssignment,
  goLoginErrorResponse,
  invalidateGoLoginProfiles,
  listGoLoginProfilesForMaster,
} from '@/lib/services/gologinService';
import { getLiveLockHolder } from '@/lib/services/gologinLockService';

// ─── Validation ─────────────────────────────────────────────────────

/** A refusal with a sentence meant for the manager, and the status to send it with. */
export class GoLoginManageError extends Error {
  constructor(message: string, readonly status = 400, readonly code?: string) {
    super(message);
    this.name = 'GoLoginManageError';
  }
}

/**
 * The management routes' one error mapping: a `GoLoginManageError` is already a
 * sentence for the manager; everything else goes through the subsystem's shared
 * `goLoginErrorResponse`, which knows the provider's failure modes.
 */
export function manageErrorResponse(err: unknown, context: string): NextResponse {
  if (err instanceof GoLoginManageError) {
    return NextResponse.json(
      err.code ? { error: err.message, code: err.code } : { error: err.message },
      { status: err.status },
    );
  }
  return goLoginErrorResponse(err, context);
}

/** How many folders one profile may be put into in one request. */
export const MAX_FOLDER_PICK = 20;

/** Control characters have no business in a label and break GoLogin's own UI. */
const CONTROL_CHARS = /[\u0000-\u001f\u007f]/;

/** Trim, collapse whitespace, and bound a label. `what` names it in the refusal. */
function cleanLabel(value: unknown, what: string, max: number): string {
  const label = typeof value === 'string' ? value.trim().replace(/\s+/g, ' ') : '';
  if (!label) throw new GoLoginManageError(`Give the ${what} a name.`);
  if (label.length > max) throw new GoLoginManageError(`Keep ${what} names under ${max} characters.`);
  if (CONTROL_CHARS.test(label)) throw new GoLoginManageError('The name contains characters GoLogin cannot store.');
  return label;
}

export function cleanProfileName(value: unknown): string {
  return cleanLabel(value, 'profile', 100);
}

export function cleanNotes(value: unknown): string {
  const notes = typeof value === 'string' ? value.replace(/\r\n/g, '\n').trim() : '';
  if (notes.length > 2000) throw new GoLoginManageError('Keep notes under 2000 characters.');
  return notes;
}

/**
 * A folder name a person may create. Bluu's own per-operator prefix is refused:
 * a folder that *looks* managed is hidden from every surface (see
 * `isManagedGoLoginFolder`), so creating one would make it vanish on arrival.
 */
export function cleanFolderName(value: unknown): string {
  const name = cleanLabel(value, 'folder', 60);
  if (isManagedGoLoginFolder(name)) {
    throw new GoLoginManageError('That prefix is reserved for Bluu’s own per-person folders.');
  }
  return name;
}

/**
 * A de-duplicated list of non-empty strings from a request body, optionally
 * filtered (e.g. `isGoLoginId`). Anything that is not an array is an empty list.
 */
export function parseIdList(value: unknown, keep: (s: string) => boolean = Boolean): string[] {
  if (!Array.isArray(value)) return [];
  return [...new Set(value.filter((v): v is string => typeof v === 'string' && !!v && keep(v)))];
}

/** A hostname or IP literal, and nothing that could smuggle a path or credentials. */
const HOST_PATTERN = /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$|^[0-9a-f:.]+$/i;

/**
 * Parse a proxy from a request body. `password` stays `undefined` when absent —
 * that is the "keep the stored one" signal on an edit, and on a create it simply
 * means no password.
 */
export function parseProxyInput(value: unknown): GoLoginProxyInput {
  const raw = value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
  const mode = raw.mode;
  if (!isGoLoginProxyMode(mode)) throw new GoLoginManageError('Choose HTTP or SOCKS5 for the proxy.');
  const host = typeof raw.host === 'string' ? raw.host.trim() : '';
  if (!host || host.length > 253 || !HOST_PATTERN.test(host)) {
    throw new GoLoginManageError('Enter the proxy’s IP address or host name — no “http://”, port or slashes.');
  }
  const port = Number(raw.port);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new GoLoginManageError('The port must be a whole number from 1 to 65535.');
  }
  const username = typeof raw.username === 'string' ? raw.username.trim() : '';
  if (username.length > 256 || CONTROL_CHARS.test(username)) {
    throw new GoLoginManageError('That proxy username is not valid.');
  }
  let password: string | undefined;
  if (typeof raw.password === 'string') {
    if (raw.password.length > 256 || CONTROL_CHARS.test(raw.password)) {
      throw new GoLoginManageError('That proxy password is not valid.');
    }
    password = raw.password;
  }
  return { mode, host, port, username, password };
}

// ─── Folder helpers ─────────────────────────────────────────────────

/**
 * The ids of Bluu's per-person folders. Folders are excluded from every
 * user-facing surface **by id** as well as by name, because a renamed operator
 * folder loses its prefix and would otherwise reappear as an ordinary folder.
 */
async function operatorFolderIds(): Promise<Set<string>> {
  const snap = await adminDb.collection(GOLOGIN_ACCOUNTS_COLLECTION).get();
  return new Set(snap.docs.map((d) => (d.data() as GoLoginAccountDoc).folderId).filter(Boolean));
}

function isUserFacingFolder(folder: GoLoginFolder, operatorIds: Set<string>): boolean {
  return !operatorIds.has(folder.id) && !isManagedGoLoginFolder(folder.name);
}

/** The user-facing folders of one master snapshot, alphabetical — the one projection. */
function userFacingRows(account: GoLoginAccountInfo, operatorIds: Set<string>): GoLoginFolderRow[] {
  return account.folders
    .filter((f) => isUserFacingFolder(f, operatorIds))
    .map((f) => ({ id: f.id, name: f.name, profileIds: f.profileIds }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Resolve ids against one snapshot, refusing anything that is not user-facing. */
function pickUserFolders(rows: GoLoginFolderRow[], folderIds: string[]): GoLoginFolderRow[] {
  const byId = new Map(rows.map((f) => [f.id, f]));
  return folderIds.map((id) => {
    const folder = byId.get(id);
    if (!folder) {
      throw new GoLoginManageError('One of those folders no longer exists, or is managed by Bluu.', 409);
    }
    return folder;
  });
}

async function loadUserFolders(force = false): Promise<GoLoginFolderRow[]> {
  const [account, operatorIds] = await Promise.all([getMasterAccount(force), operatorFolderIds()]);
  return userFacingRows(account, operatorIds);
}

/**
 * The user-facing folders **with who each is shared with** — for every read a
 * folder picker makes. A shared folder is live, so adding a profile to it hands
 * that profile to everyone on this list; the pickers must be able to say so.
 *
 * Costs the memoised `GET /workspaces/{wid}` on top of the folder read, one read
 * of `gologin-accounts` (which `operatorFolderIds` needed anyway) and one batched
 * read of display names — never a read per member (rule 9).
 */
async function loadUserFoldersWithShares(force = false): Promise<GoLoginFolderRow[]> {
  const [account, workspace, accountsSnap] = await Promise.all([
    getMasterAccount(force),
    getWorkspace(force),
    adminDb.collection(GOLOGIN_ACCOUNTS_COLLECTION).get(),
  ]);
  const accounts = accountsSnap.docs.map((d) => d.data() as GoLoginAccountDoc);
  const rows = userFacingRows(account, new Set(accounts.map((a) => a.folderId).filter(Boolean)));

  const userDocs = accounts.length
    ? await adminDb.getAll(...accounts.map((a) => adminDb.collection('users').doc(a.uid)))
    : [];
  const nameByUid = new Map(
    userDocs.filter((d) => d.exists).map((d) => [d.id, (d.data() as { displayName?: string }).displayName]),
  );

  const namesByFolder = new Map<string, string[]>();
  for (const a of accounts) {
    const seat = findMember(workspace, a.glEmail);
    if (!seat) continue;
    const name = nameByUid.get(a.uid) || a.glEmail;
    for (const folderName of seat.folderNames) {
      const list = namesByFolder.get(folderName);
      if (list) list.push(name);
      else namesByFolder.set(folderName, [name]);
    }
  }
  return rows.map((f) => ({
    ...f,
    sharedWith: (namesByFolder.get(f.name) ?? []).sort((a, b) => a.localeCompare(b)),
  }));
}

/** Refuse to change a profile someone has open — see `getLiveLockHolder`. */
async function assertNotInUse(profileId: string, verb: string): Promise<void> {
  const holder = await getLiveLockHolder(profileId);
  if (holder) {
    throw new GoLoginManageError(
      `${holder.displayName || 'Someone'} has this profile open. ${verb} it once they have closed it.`,
      409,
      'in-use',
    );
  }
}

/** A profile was created or deleted: every listing and the folder tree are stale. */
function invalidateAfterStructuralWrite(): void {
  invalidateMasterAccount();
  invalidateGoLoginProfiles();
}

// ─── Profiles ───────────────────────────────────────────────────────

export interface CreateProfileResult {
  profile: GoLoginProfile;
  /** Steps after creation that did not land — the profile itself is fine. */
  warnings: string[];
}

/**
 * Create a profile: GoLogin's defaults for the chosen OS, then the proxy, then
 * folders.
 *
 * The order is load-bearing. The proxy step is the one that **must** succeed —
 * a profile without its proxy runs on whatever IP the operator's desk has — so a
 * failure there deletes the profile and reports the failure, rather than leaving
 * a trap in the list. Folder steps after it are conveniences: a failure is a
 * warning, and the profile stands.
 *
 * "Without proxy" is written explicitly (`mode: 'none'`) rather than left to the
 * template, because a workspace's default-settings template can itself carry a
 * proxy, and a person who chose "no proxy" must get none.
 */
export async function createProfile(params: {
  callerUid: string;
  name: string;
  os: GoLoginOsChoice;
  proxy: GoLoginProxyInput | null;
  folderIds: string[];
}): Promise<CreateProfileResult> {
  const { callerUid, name, os, proxy, folderIds } = params;
  const folders = folderIds.length ? pickUserFolders(await loadUserFolders(), folderIds) : [];
  const client = getMasterGoLoginClient();
  const choice = GOLOGIN_OS_CHOICES[os];

  const profileId = await client.quickCreateProfile({
    name,
    os: choice.os,
    osSpec: choice.osSpec,
    workspaceId: await getWorkspaceId(),
  });
  // A new profile exists: the tree and every listing are stale from here on,
  // whatever happens next.
  invalidateAfterStructuralWrite();

  try {
    await client.setProfileProxy(profileId, proxy);
  } catch (err) {
    // Roll back. A proxy-less profile would launch on the operator's own IP.
    try {
      await client.deleteProfiles([profileId]);
    } catch (cleanupErr) {
      console.error('[gologin] could not remove a profile after its proxy failed', profileId, cleanupErr);
      throw new GoLoginManageError(
        `The proxy could not be attached, and the half-created profile “${name}” could not be removed. Delete it before anyone launches it.`,
        502,
      );
    }
    const reason = err instanceof Error ? err.message : 'unknown error';
    throw new GoLoginManageError(`The proxy could not be attached, so the profile was not created. (${reason})`, 502);
  }

  const warnings: string[] = [];
  for (const folder of folders) {
    try {
      await client.setFolderProfiles(folder.name, [profileId], 'add');
    } catch (err) {
      console.error('[gologin] could not add a new profile to', folder.name, err);
      warnings.push(`It could not be added to ${folder.name}.`);
    }
  }

  // A non-admin sees the workspace through their own folder, so a profile they
  // just made would otherwise not appear in their own list at all.
  if (!(await isGoLoginAdmin(callerUid))) {
    try {
      await changeAssignment({ uid: callerUid, profileIds: [profileId], action: 'add' });
    } catch (err) {
      console.error('[gologin] could not share a new profile with its creator', err);
      warnings.push('It could not be added to your own list — ask an admin to share it with you.');
    }
  }

  let profile: GoLoginProfile;
  try {
    profile = await client.getProfile(profileId);
  } catch {
    // Created and configured; only the read-back failed. A refresh finds it.
    profile = {
      id: profileId,
      name,
      notes: '',
      os: choice.os,
      osSpec: choice.osSpec,
      browserType: 'chrome',
      proxyType: proxy?.mode ?? 'none',
      proxyRegion: '',
      proxyHost: proxy?.host ?? '',
      isRunning: false,
      runningUserEmail: '',
      folders: folders.map((f) => f.name),
      createdAtMs: Date.now(),
      updatedAtMs: Date.now(),
      lastActivityMs: null,
    };
  }
  return { profile, warnings };
}

/**
 * The Edit panel's read, plus the folder list it picks from — one request, so
 * opening the panel does not also fetch the folders separately.
 */
export async function getProfileForEdit(profileId: string): Promise<{
  profile: GoLoginProfileDetail;
  /** The user-facing folders the profile currently sits in. */
  folderIds: string[];
  /** Every user-facing folder, for the panel's checklist. */
  folders: GoLoginFolderRow[];
}> {
  const [profile, folders] = await Promise.all([
    getMasterGoLoginClient().getProfileDetail(profileId),
    loadUserFoldersWithShares(),
  ]);
  // Membership from the folder tree, not the profile's own `folders` names —
  // the tree is keyed by id, which is what every write addresses.
  return {
    profile: { ...profile, folders: profile.folders.filter((n) => !isManagedGoLoginFolder(n)) },
    folderIds: folders.filter((f) => f.profileIds.includes(profileId)).map((f) => f.id),
    folders,
  };
}

/**
 * Put a profile in exactly these user-facing folders — the one folder diff,
 * used by Edit profile and by Add to folder. Bluu's per-person folders are never
 * touched: a profile's sharing is the Sharing dialog's business.
 *
 * One forced read (the diff must be against GoLogin's truth, not a 60s-old
 * guess), then one write per changed folder, each patched into the memo.
 * Returns the user-facing folder names the profile ends up in.
 */
export async function setProfileFolders(profileId: string, folderIds: string[]): Promise<string[]> {
  const rows = await loadUserFolders(true);
  const wanted = pickUserFolders(rows, folderIds);
  const wantedIds = new Set(wanted.map((f) => f.id));
  const current = rows.filter((f) => f.profileIds.includes(profileId));
  const currentIds = new Set(current.map((f) => f.id));
  const client = getMasterGoLoginClient();

  for (const folder of wanted) {
    if (currentIds.has(folder.id)) continue;
    await client.setFolderProfiles(folder.name, [profileId], 'add');
    applyFolderMembership(folder.id, [profileId], 'add');
  }
  for (const folder of current) {
    if (wantedIds.has(folder.id)) continue;
    await client.setFolderProfiles(folder.name, [profileId], 'remove');
    applyFolderMembership(folder.id, [profileId], 'remove');
  }
  invalidateGoLoginProfiles();
  return wanted.map((f) => f.name);
}

export interface ProfileUpdate {
  name?: string;
  notes?: string;
  /** `null` removes the proxy; `undefined` leaves it alone. */
  proxy?: GoLoginProxyInput | null;
  /** The complete set of user-facing folders the profile should be in. */
  folderIds?: string[];
}

/**
 * Apply an edit, one field-scoped endpoint per changed field.
 *
 * **Notes go first**, because they are the one write that sends the whole
 * document back: done after the name or proxy it would PUT the *old* name and
 * proxy over the new ones. Every later step touches only its own field.
 */
export async function updateProfile(profileId: string, update: ProfileUpdate): Promise<GoLoginProfile> {
  await assertNotInUse(profileId, 'Edit');
  const client = getMasterGoLoginClient();

  if (update.notes !== undefined) await client.setProfileNotes(profileId, update.notes);
  if (update.name !== undefined) await client.renameProfile(profileId, update.name);
  if (update.proxy !== undefined) await client.setProfileProxy(profileId, update.proxy);
  if (update.folderIds !== undefined) await setProfileFolders(profileId, update.folderIds);

  invalidateGoLoginProfiles();
  return client.getProfile(profileId);
}

/**
 * Delete a profile. GoLogin keeps it restorable, which is what makes the Undo
 * on the toast an honest one — see `restoreProfile`.
 */
export async function deleteProfile(profileId: string): Promise<void> {
  await assertNotInUse(profileId, 'Delete');
  await getMasterGoLoginClient().deleteProfiles([profileId]);
  invalidateAfterStructuralWrite();
}

export async function restoreProfile(profileId: string): Promise<void> {
  await getMasterGoLoginClient().restoreProfiles([profileId], await getWorkspaceId());
  invalidateAfterStructuralWrite();
}

// ─── Folders ────────────────────────────────────────────────────────

/** Every user-facing folder, alphabetical, with who each is shared with. */
export function listUserFolders(force = false): Promise<GoLoginFolderRow[]> {
  return loadUserFoldersWithShares(force);
}

/**
 * Create a folder. Names are unique case-insensitively across **every** folder,
 * including hidden ones: GoLogin addresses folders by name, so two folders that
 * differ only in case make every later write ambiguous. The pre-check reads the
 * memo; the read-back after the create is the one that must be fresh.
 */
export async function createFolder(name: string): Promise<GoLoginFolderRow> {
  const key = name.toLocaleLowerCase();
  if ((await getMasterAccount()).folders.some((f) => f.name.toLocaleLowerCase() === key)) {
    throw new GoLoginManageError(`A folder called “${name}” already exists.`, 409);
  }
  await getMasterGoLoginClient().createFolder(name);
  invalidateMasterAccount();
  // The create endpoint returns no id — read it back by the name just written.
  const folder = (await getMasterAccount(true)).folders.find((f) => f.name === name);
  if (!folder) throw new GoLoginManageError('GoLogin did not confirm the new folder. Refresh and check.', 502);
  return { id: folder.id, name: folder.name, profileIds: folder.profileIds };
}

/**
 * Delete a folder. Its profiles stay — a folder is a label, not a container.
 *
 * Members scoped to it lose that scope **first**, by re-writing each one's
 * folder list without it. Deleting the folder out from under a member's scope
 * leaves GoLogin holding a reference to a name that no longer exists, and what
 * it does with that is undocumented; doing it in this order means we never find
 * out. Sequential, like every member write.
 */
export async function deleteFolder(folderId: string): Promise<{ unsharedFrom: number }> {
  const [folder] = pickUserFolders(await loadUserFolders(), [folderId]);
  const workspace = await getWorkspace(true);
  const workspaceId = await getWorkspaceId();
  const client = getMasterGoLoginClient();

  let unsharedFrom = 0;
  for (const member of workspace.members) {
    if (!member.folderNames.includes(folder.name)) continue;
    await client.updateWorkspaceMember({
      workspaceId,
      memberId: member.id,
      role: GOLOGIN_MEMBER_ROLE,
      folderNames: member.folderNames.filter((n) => n !== folder.name),
    });
    unsharedFrom++;
  }
  if (unsharedFrom) invalidateWorkspace();

  await client.deleteFolder(folder.name);
  invalidateAfterStructuralWrite();
  return { unsharedFrom };
}

/** Add or remove profiles from one user-facing folder. */
export async function setFolderProfiles(
  folderId: string,
  profileIds: string[],
  action: 'add' | 'remove',
): Promise<void> {
  const [folder] = pickUserFolders(await loadUserFolders(), [folderId]);
  await getMasterGoLoginClient().setFolderProfiles(folder.name, profileIds, action);
  applyFolderMembership(folder.id, profileIds, action);
  invalidateGoLoginProfiles();
}

// ─── Sharing ────────────────────────────────────────────────────────

/**
 * Everything the Sharing dialog renders.
 *
 * Two kinds of access, and the dialog shows both:
 *   • **A shared folder is live.** The member's seat is scoped to it, so a
 *     profile added to that folder later reaches them with no further action.
 *   • **A shared profile is a single grant**, written into their personal
 *     folder. It is how one profile reaches someone without its whole folder.
 *
 * Admins are not members — they run the workspace on the master token and see
 * everything — so they are never listed.
 */
export async function getSharingOverview(force = false): Promise<GoLoginSharingOverview> {
  const [account, workspace, list, accountsSnap] = await Promise.all([
    getMasterAccount(force),
    getWorkspace(force),
    listGoLoginProfilesForMaster(force),
    adminDb.collection(GOLOGIN_ACCOUNTS_COLLECTION).get(),
  ]);
  const accounts = accountsSnap.docs.map((d) => d.data() as GoLoginAccountDoc);
  const folders = userFacingRows(account, new Set(accounts.map((a) => a.folderId).filter(Boolean)));
  const folderIdByName = new Map(folders.map((f) => [f.name, f.id]));
  const folderById = new Map(account.folders.map((f) => [f.id, f]));

  // One batched read for the names (rule 9) — never a lookup per member.
  const userDocs = accounts.length
    ? await adminDb.getAll(...accounts.map((a) => adminDb.collection('users').doc(a.uid)))
    : [];
  const userByUid = new Map(
    userDocs
      .filter((d) => d.exists)
      .map((d) => [d.id, d.data() as { displayName?: string; isArchived?: boolean; groups?: string[] }]),
  );

  const members: GoLoginSharingMember[] = accounts
    .filter((a) => {
      const user = userByUid.get(a.uid);
      return !user?.isArchived && !usesMasterGoLoginToken(user);
    })
    .map((a) => {
      const seat = findMember(workspace, a.glEmail);
      return {
        uid: a.uid,
        displayName: userByUid.get(a.uid)?.displayName ?? a.uid,
        glEmail: a.glEmail,
        hasSeat: !!seat,
        profileIds: folderById.get(a.folderId)?.profileIds ?? [],
        folderIds: (seat?.folderNames ?? [])
          .map((name) => folderIdByName.get(name))
          .filter((id): id is string => !!id),
      };
    })
    .sort((a, b) => a.displayName.localeCompare(b.displayName));

  return {
    members,
    folders,
    profiles: list.profiles.map((p) => ({
      id: p.id,
      name: p.name,
      os: p.os,
      osSpec: p.osSpec,
      folders: p.folders.filter((n) => !isManagedGoLoginFolder(n)),
    })),
    truncated: list.truncated,
    fetchedAtMs: list.fetchedAtMs,
  };
}

export interface ShareOutcome {
  /** Members the change landed for. */
  done: number;
  /** Members it did not land for, with why — one bad seat must not stop the rest. */
  failed: { uid: string; reason: string }[];
}

/**
 * Share (or unshare) folders with members, **live**: each member's seat is
 * re-scoped to include (or exclude) the folders.
 *
 * Their own personal folder is always kept in the scope, resolved by id — it is
 * how every individually shared profile reaches them, and dropping it would
 * silently revoke all of those. The member list is read fresh (`force`) because
 * the write replaces the whole scope: a 60s-old snapshot would undo a change
 * someone else made in the last minute. Account rows are read in one batch.
 */
export async function shareFolders(params: {
  uids: string[];
  folderIds: string[];
  action: 'add' | 'remove';
}): Promise<ShareOutcome> {
  const { uids, folderIds, action } = params;
  const [rows, workspace, workspaceId, account, accountSnaps] = await Promise.all([
    loadUserFolders(),
    getWorkspace(true),
    getWorkspaceId(),
    getMasterAccount(),
    adminDb.getAll(...uids.map((uid) => adminDb.collection(GOLOGIN_ACCOUNTS_COLLECTION).doc(uid))),
  ]);
  const names = pickUserFolders(rows, folderIds).map((f) => f.name);
  const accountByUid = new Map(
    accountSnaps.filter((s) => s.exists).map((s) => [s.id, s.data() as GoLoginAccountDoc]),
  );
  const folderNameById = new Map(account.folders.map((f) => [f.id, f.name]));
  const client = getMasterGoLoginClient();
  const outcome: ShareOutcome = { done: 0, failed: [] };

  for (const uid of uids) {
    try {
      if (await isGoLoginAdmin(uid)) throw new Error('Admins already see every profile.');
      const row = accountByUid.get(uid);
      if (!row?.glEmail) throw new Error('They do not hold a GoLogin seat.');
      const seat = findMember(workspace, row.glEmail);
      if (!seat) throw new Error('Their seat has been removed in GoLogin.');

      const next = new Set(seat.folderNames);
      for (const name of names) {
        if (action === 'add') next.add(name);
        else next.delete(name);
      }
      const personal = row.folderId ? folderNameById.get(row.folderId) : undefined;
      if (personal) next.add(personal);

      await client.updateWorkspaceMember({
        workspaceId,
        memberId: seat.id,
        role: GOLOGIN_MEMBER_ROLE,
        folderNames: [...next],
      });
      invalidateGoLoginProfiles(uid);
      outcome.done++;
    } catch (err) {
      outcome.failed.push({ uid, reason: err instanceof Error ? err.message : 'Unknown error' });
    }
  }
  invalidateWorkspace();
  return outcome;
}

/**
 * Share (or unshare) individual profiles with members — their personal folder.
 *
 * ⚠ Unsharing a profile here does not revoke it if the member *also* reaches it
 * through a shared folder. The dialog shows that case ("via REPOST") rather
 * than pretending the toggle removed access it cannot remove.
 */
export async function shareProfiles(params: {
  uids: string[];
  profileIds: string[];
  action: 'add' | 'remove';
}): Promise<ShareOutcome> {
  const { uids, profileIds, action } = params;
  const outcome: ShareOutcome = { done: 0, failed: [] };
  for (const uid of uids) {
    try {
      await changeAssignment({ uid, profileIds, action });
      outcome.done++;
    } catch (err) {
      outcome.failed.push({ uid, reason: err instanceof Error ? err.message : 'Unknown error' });
    }
  }
  return outcome;
}
