'use client';

import { useState } from 'react';
import { Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { useAuthFetch } from '@/hooks/useAuthFetch';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  GOLOGIN_OS_CHOICES,
  type GoLoginOsChoice,
  type GoLoginProfile,
} from '@/lib/gologin/types';
import { FIELD, LABEL, PRIMARY_BUTTON } from '../_lib/manage';
import { useManagedFolders } from '../_lib/useManagedFolders';
import FolderChecklist from './FolderChecklist';
import OsIcon from './OsIcon';
import ProxyFields, {
  EMPTY_PROXY,
  proxyComplete,
  proxyPayload,
  type ProxyDraft,
} from './ProxyFields';

/** One line under each OS, so the choice is made on what it is, not its name. */
const OS_HINT: Record<GoLoginOsChoice, string> = {
  win10: 'The most common desktop',
  win11: 'Newer Windows fingerprint',
  'mac-m1': 'Apple Silicon Mac',
  'mac-intel': 'Older Intel Mac',
};

const OS_ORDER: GoLoginOsChoice[] = ['win10', 'win11', 'mac-m1', 'mac-intel'];

/** A new profile is in no folder yet, so every tick is a new grant. */
const NO_FOLDERS: ReadonlySet<string> = new Set();

/**
 * New Profile — the only place in Bluu a GoLogin profile is born.
 *
 * ## What is configurable, and why nothing else is
 *
 * Name, OS, proxy and folders. Everything else — user agent, resolution,
 * WebGL, fonts, canvas, CPU and memory — is **generated by GoLogin** for the
 * chosen OS from the workspace's own default settings (`POST /browser/quick`).
 * That is deliberate, not a missing feature: a fingerprint assembled field by
 * field is how an internally inconsistent one happens (a Mac user agent with a
 * Windows GPU string), and an inconsistent fingerprint is what gets an account
 * flagged. The OS is the one choice that decides the rest.
 *
 * ## The proxy
 *
 * There is no pre-flight test: the team's proxies are private and only admit
 * the operators' own connections, so a test from Bluu's server failed on
 * working proxies (removed 2026-09-30). The proxy is tested for real when the
 * profile is first launched, and a failure there is shown on the row as a
 * proxy failure. Server-side, a failure to *attach* the proxy deletes the new
 * profile rather than leaving it on a desk's real IP.
 */
export default function NewProfileDialog({
  open,
  onOpenChange,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: (profile: GoLoginProfile) => void;
}) {
  const authFetch = useAuthFetch();
  const [name, setName] = useState('');
  const [os, setOs] = useState<GoLoginOsChoice>('win10');
  const [proxy, setProxy] = useState<ProxyDraft>(EMPTY_PROXY);
  const [folderIds, setFolderIds] = useState<Set<string>>(new Set());
  const [saving, setSaving] = useState(false);
  const folders = useManagedFolders(open);

  const reset = () => {
    setName('');
    setOs('win10');
    setProxy(EMPTY_PROXY);
    setFolderIds(new Set());
  };

  /** Why Create is disabled, said beside it — a greyed button explains nothing. */
  const blocker = !name.trim()
    ? 'Name the profile.'
    : proxy.enabled && !proxyComplete(proxy)
      ? 'Enter the proxy’s IP and port.'
      : null;
  const canCreate = !blocker && !saving;

  const submit = async () => {
    if (!canCreate) return;
    setSaving(true);
    try {
      const result: { profile: GoLoginProfile; warnings: string[] } = await authFetch(
        '/api/gologin/manage/profiles',
        {
          method: 'POST',
          body: JSON.stringify({
            name: name.trim(),
            os,
            proxy: proxyPayload(proxy),
            folderIds: [...folderIds],
          }),
        },
      );
      onCreated(result.profile);
      if (result.warnings.length) {
        toast.warning(`Created ${result.profile.name}, with a problem`, {
          description: result.warnings.join(' '),
          duration: 10_000,
        });
      } else {
        toast.success(`Created ${result.profile.name}.`);
      }
      reset();
      onOpenChange(false);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Could not create the profile.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        // Closing mid-write would leave the reader not knowing whether it landed.
        if (saving) return;
        onOpenChange(next);
      }}
    >
      <DialogContent className="flex max-h-[min(88vh,820px)] flex-col gap-0 overflow-hidden p-0 sm:max-w-2xl">
        <DialogHeader className="shrink-0 border-b border-white/[0.07] px-6 pb-4 pt-5 text-left">
          <DialogTitle className="text-lg font-semibold text-white">New profile</DialogTitle>
          <DialogDescription className="text-[11px] text-zinc-400">
            Choose the name, operating system and proxy. GoLogin generates the rest of the
            fingerprint to match the OS, from the workspace&rsquo;s default settings.
          </DialogDescription>
        </DialogHeader>

        <form
          className="min-h-0 flex-1 space-y-6 overflow-y-auto px-6 py-5"
          onSubmit={(e) => {
            e.preventDefault();
            void submit();
          }}
          id="new-profile-form"
        >
          <label className="block">
            <span className={LABEL}>Profile name</span>
            <Input
              value={name}
              onChange={(e) => setName(e.target.value)}
              maxLength={100}
              placeholder="e.g. Cole · Instagram"
              autoFocus
              className={`h-9 ${FIELD}`}
            />
          </label>

          <fieldset>
            <legend className={LABEL}>Operating system</legend>
            <RadioGroup
              value={os}
              onValueChange={(value) => setOs(value as GoLoginOsChoice)}
              className="grid grid-cols-2 gap-2 sm:grid-cols-4"
            >
              {OS_ORDER.map((choice) => {
                const on = os === choice;
                return (
                  <label
                    key={choice}
                    // Selection = Action Blue tint + border + weight: three cues,
                    // never an overlay step a hover can imitate (DESIGN.md §5).
                    className={`flex cursor-pointer items-start gap-2.5 rounded-lg border px-3 py-2.5 transition-colors ${
                      on
                        ? 'border-[#3b82f6]/50 bg-[#3b82f6]/15'
                        : 'border-white/[0.07] bg-white/[0.025] hover:bg-white/[0.055]'
                    }`}
                  >
                    <RadioGroupItem
                      value={choice}
                      className="mt-0.5 data-[state=checked]:border-[#3b82f6] [&_svg]:fill-[#3b82f6]"
                    />
                    <span className="min-w-0">
                      <span className={`flex items-center gap-1.5 text-sm ${on ? 'font-semibold text-white' : 'font-medium text-zinc-300'}`}>
                        {/* Mark and words together here: the card must tell
                            Windows 10 from 11 and M1 from Intel, which a mark
                            alone cannot. */}
                        <OsIcon os={GOLOGIN_OS_CHOICES[choice].os} osSpec={GOLOGIN_OS_CHOICES[choice].osSpec} className="size-4" />
                        <span>{GOLOGIN_OS_CHOICES[choice].label}</span>
                      </span>
                      <span className="block text-[11px] text-zinc-400">{OS_HINT[choice]}</span>
                    </span>
                  </label>
                );
              })}
            </RadioGroup>
            <p className="mt-1.5 text-[11px] text-zinc-400">
              This is the device the profile pretends to be — it runs on any computer. It cannot be
              changed later without risking the account inside it.
            </p>
          </fieldset>

          <fieldset>
            <legend className={LABEL}>Connection</legend>
            <ProxyFields draft={proxy} onChange={setProxy} />
          </fieldset>

          <fieldset>
            <legend className={LABEL}>
              Folders <span className="font-normal">· optional</span>
            </legend>
            <FolderChecklist
              folders={folders.folders}
              loading={folders.loading}
              error={folders.error}
              selected={folderIds}
              initial={NO_FOLDERS}
              maxHeightClass="max-h-40"
              onChange={setFolderIds}
            />
          </fieldset>
        </form>

        <DialogFooter className="shrink-0 items-center border-t border-white/[0.07] px-6 py-3 sm:justify-between">
          <p className="text-[11px] text-zinc-400" aria-live="polite">
            {blocker ?? 'Ready to create.'}
          </p>
          <div className="flex gap-2">
            <Button type="button" variant="ghost" onClick={() => onOpenChange(false)} disabled={saving}>
              Cancel
            </Button>
            <Button type="submit" form="new-profile-form" className={PRIMARY_BUTTON} disabled={!canCreate}>
              {saving && <Loader2 className="activity-spinner size-3.5 animate-spin" aria-hidden />}
              {saving ? 'Creating…' : 'Create profile'}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
